# ★「work_segment.py」と同期を取ること
$workSegments = @(
  @{ Key = "OFFICE"; Label = "出勤" },
  @{ Key = "REMOTE"; Label = "出勤(在宅)" },
  @{ Key = "HOLIDAY"; Label = "公休" },
  @{ Key = "SUBSTITUTE"; Label = "振休" },
  @{ Key = "PAID_LEAVE"; Label = "有休" },
  @{ Key = "SPECIAL_LEAVE"; Label = "特休" },
  @{ Key = "ABSENCE"; Label = "欠勤" },
  @{ Key = "SUBSTITUTE_WORK"; Label = "振出(日曜以外)" },
  @{ Key = "SUBSTITUTE_WORK_SUN"; Label = "振出(日曜)" },
  @{ Key = "HALF_SUBSTITUTE_WORK"; Label = "半日振出(日曜以外)" },
  @{ Key = "HALF_SUBSTITUTE_WORK_SUN"; Label = "半日振出(日曜)" },
  @{ Key = "TRAINING"; Label = "終日研修" },
  @{ Key = "SUMMER_LEAVE"; Label = "夏季休暇" },
  @{ Key = "HALF_OFFICE_REMOTE"; Label = "半日出社+半日在宅" },
  @{ Key = "HALF_PAID_OFFICE"; Label = "半日有給+半日出社" },
  @{ Key = "HALF_PAID_REMOTE"; Label = "半日有給+半日在宅" },
  @{ Key = "HALF_SUBSTITUTE_OFFICE"; Label = "半日振休+半日出社" },
  @{ Key = "HALF_SUBSTITUTE_REMOTE"; Label = "半日振休+半日在宅" },
  @{ Key = "REMOTE_SUBSTITUTE"; Label = "在宅振出(日曜以外)" },
  @{ Key = "REMOTE_SUBSTITUTE_SUN"; Label = "在宅振出(日曜)" },
  @{ Key = "HALF_HOLIDAY_REMOTE_SUB"; Label = "半日公休+半日在宅振出(日曜以外)" },
  @{ Key = "HALF_HOLIDAY_REMOTE_SUB_SUN"; Label = "半日公休+半日在宅振出(日曜)" }
)
