// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadData() {
  return window['go']['main']['App']['LoadData']();
}

export function RegisterRecords(arg1) {
  return window['go']['main']['App']['RegisterRecords'](arg1);
}

export function SavePreset(arg1, arg2) {
  return window['go']['main']['App']['SavePreset'](arg1, arg2);
}

export function UpdatePreset(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdatePreset'](arg1, arg2, arg3);
}
