// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LoadData():Promise<main.InitialData>;

export function RegisterRecords(arg1:Array<main.Record>):Promise<string>;

export function SavePreset(arg1:string,arg2:main.Record):Promise<void>;

export function UpdatePreset(arg1:string,arg2:string,arg3:main.Record):Promise<void>;
